# https://github.com/marketplace/actions/pypi-github-auto-release

name: Auto-publish

on: [push, workflow_dispatch]

jobs:
  # Auto-publish when version is increased
  build-and-publish-job:
    # Only publish on `master` branch when tagged
    if: github.ref == 'refs/heads/master' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    permissions:  # Don't forget permissions
      contents: write

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: >-
        python -m pip install build --user
    - name: Build
      run: >-
        python -m build --sdist --wheel --outdir dist/ .
    - uses: etils-actions/pypi-auto-publish@v1
      with:
        pypi-token: ${{ secrets.PYPI_API_TOKEN }}
        gh-token: ${{ secrets.GITHUB_TOKEN }}
        parse-changelog: false   # requires CHANGELOG.md in appropriate format
