
jobs:
- job: test
  strategy:
    matrix:
      Windows py37:
        IMAGE_NAME: 'windows-latest'
        PYTHON_VERSION: '3.7'
        TOX_CMD: 'py37'
      Windows py38:
        IMAGE_NAME: 'windows-latest'
        PYTHON_VERSION: '3.8'
        TOX_CMD: 'py38'
      Windows py39:
        IMAGE_NAME: 'windows-latest'
        PYTHON_VERSION: '3.9'
        TOX_CMD: 'py39'
      Windows py310:
        IMAGE_NAME: 'windows-latest'
        PYTHON_VERSION: '3.10'
        TOX_CMD: 'py310'
      OSX py37:
        IMAGE_NAME: 'macOS-latest'
        PYTHON_VERSION: '3.7'
        TOX_CMD: 'py37'
      OSX py38:
        IMAGE_NAME: 'macOS-latest'
        PYTHON_VERSION: '3.8'
        TOX_CMD: 'py38'
      OSX py39:
        IMAGE_NAME: 'macOS-latest'
        PYTHON_VERSION: '3.9'
        TOX_CMD: 'py39'
      OSX py310:
        IMAGE_NAME: 'macOS-latest'
        PYTHON_VERSION: '3.10'
        TOX_CMD: 'py310'
      Linux py37:
        IMAGE_NAME: 'ubuntu-latest'
        PYTHON_VERSION: '3.7'
        TOX_CMD: 'py37'
      Linux py38:
        IMAGE_NAME: 'ubuntu-latest'
        PYTHON_VERSION: '3.8'
        TOX_CMD: 'py38'
      Linux py39:
        IMAGE_NAME: 'ubuntu-latest'
        PYTHON_VERSION: '3.9'
        TOX_CMD: 'py39'
      Linux py310:
        IMAGE_NAME: 'ubuntu-latest'
        PYTHON_VERSION: '3.10'
        TOX_CMD: 'py310'
      Linux numpy_120:
        IMAGE_NAME: 'ubuntu-latest'
        PYTHON_VERSION: '3.9'
        TOX_CMD: 'numpy-120'
      Linux numpy_121:
        IMAGE_NAME: 'ubuntu-latest'
        PYTHON_VERSION: '3.9'
        TOX_CMD: 'numpy-121'
      Linux numpy_122:
        IMAGE_NAME: 'ubuntu-latest'
        PYTHON_VERSION: '3.10'
        TOX_CMD: 'numpy-122'
      Linux numpy_123:
        IMAGE_NAME: 'ubuntu-latest'
        PYTHON_VERSION: '3.10'
        TOX_CMD: 'numpy-123'
      Linux tensorflow_26:
        IMAGE_NAME: 'ubuntu-latest'
        PYTHON_VERSION: '3.7'
        TOX_CMD: 'tensorflow-26'
      Linux tensorflow_27:
        IMAGE_NAME: 'ubuntu-latest'
        PYTHON_VERSION: '3.8'
        TOX_CMD: 'tensorflow-27'
      Linux tensorflow-28:
        IMAGE_NAME: 'ubuntu-latest'
        PYTHON_VERSION: '3.9'
        TOX_CMD: 'tensorflow-28'
      Linux tensorflow_29:
        IMAGE_NAME: 'ubuntu-latest'
        PYTHON_VERSION: '3.10'
        TOX_CMD: 'tensorflow-29'
      Linux setup:
        IMAGE_NAME: 'ubuntu-latest'
        PYTHON_VERSION: '3.9'
        TOX_CMD: 'setup'
      Linux flake8:
        IMAGE_NAME: 'ubuntu-latest'
        PYTHON_VERSION: '3.9'
        TOX_CMD: 'flake8'
      Linux black:
        IMAGE_NAME: 'ubuntu-latest'
        PYTHON_VERSION: '3.9'
        TOX_CMD: 'black'
      Linux coverage:
        IMAGE_NAME: 'ubuntu-latest'
        PYTHON_VERSION: '3.9'
        TOX_CMD: 'coverage'
  pool:
    vmImage: $(IMAGE_NAME)
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(PYTHON_VERSION)
    - bash: pip install tox
    - bash: tox -e $TOX_CMD
- job: test_pre_commit_39
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.9'
    - bash: bash ./tests/check_pre_commit.sh
- job: test_pre_commit_310
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
    - bash: bash ./tests/check_pre_commit.sh
